project_id = "xhdmdkxslvyuoqpnuehu"

[functions.bulk-delete-cards]
verify_jwt = false

[functions.create-gacha-slots]
verify_jwt = false

[functions.play-gacha]
verify_jwt = false

[functions.bulk-convert-points]
verify_jwt = false

[functions.auto-convert-expired-slots]
verify_jwt = false

[functions.check-ip-access]
verify_jwt = false

[functions.import-user-migrations]
verify_jwt = false

[functions.import-transactions]
verify_jwt = false

[functions.import-inventory]
verify_jwt = false

[functions.bulk-create-profiles]
verify_jwt = false

[functions.delete-import-history]
verify_jwt = false

[functions.import-daily-analytics]
verify_jwt = false

[functions.import-shipping-history]
verify_jwt = false

[functions.import-point-conversions]
verify_jwt = false

[functions.import-pending-shipments]
verify_jwt = false
