project_id = "xhdmdkxslvyuoqpnuehu"

[functions.bulk-delete-cards]
verify_jwt = false

[functions.create-gacha-slots]
verify_jwt = false

[functions.play-gacha]
verify_jwt = false

[functions.bulk-convert-points]
verify_jwt = false

[functions.auto-convert-expired-slots]
verify_jwt = false
